import { ERPDatabase, User } from '../types';

export const DEFAULT_USERS: User[] = [
  {
    id: 'user-01',
    name: 'Eng. Carlos Eduardo Silva',
    email: 'carlos.silva@fabripcp.ind.br',
    role: 'RESPONSAVEL_TECNICO',
    roleTitle: 'Responsável Técnico / Engenheiro Mecânico',
    registrationNumber: 'CREA-SP 506.912/D',
  },
  {
    id: 'user-02',
    name: 'Mariana Duarte Mendes',
    email: 'mariana.pcp@fabripcp.ind.br',
    role: 'GERENTE_PCP',
    roleTitle: 'Coordenadora de Planejamento e Controle da Produção',
    registrationNumber: 'CRA-SP 148.203',
  },
  {
    id: 'user-03',
    name: 'Roberto Antunes Costa',
    email: 'roberto.producao@fabripcp.ind.br',
    role: 'OPERADOR_LIDER',
    roleTitle: 'Líder Geral de Produção e Usinagem',
    registrationNumber: 'MAT-0891',
  },
];

export const INITIAL_DATABASE: ERPDatabase = {
  users: DEFAULT_USERS,
  currentUser: DEFAULT_USERS[0],
  
  suppliers: [
    {
      id: 'sup-01',
      code: 'FORN-001',
      name: 'Aços Brasil Tubos & Perfis S/A',
      tradeName: 'Aços Brasil',
      document: '12.345.678/0001-90',
      contactPerson: 'Marcos Vinicius',
      email: 'vendas@acosbrasil.com.br',
      phone: '(11) 3456-7890',
      city: 'Guarulhos',
      state: 'SP',
      deliveryLeadTimeDays: 4,
      suppliedCategories: ['Tubos de Aço', 'Chapas Metálicas', 'Perfis'],
      notes: 'Fornecedor homologado ISO 9001. Pagamento 30 DDL.',
      createdAt: '2026-01-10T08:00:00Z',
    },
    {
      id: 'sup-02',
      code: 'FORN-002',
      name: 'Nacional Fixadores e Ferragens Eireli',
      tradeName: 'Fixadores Nacional',
      document: '98.765.432/0001-21',
      contactPerson: 'Patrícia Souza',
      email: 'comercial@fixadoresnacional.com.br',
      phone: '(19) 3211-4455',
      city: 'Campinas',
      state: 'SP',
      deliveryLeadTimeDays: 2,
      suppliedCategories: ['Parafusos', 'Porcas', 'Arruelas', 'Rebites'],
      notes: 'Entrega rápida e pontual.',
      createdAt: '2026-01-12T09:30:00Z',
    },
    {
      id: 'sup-03',
      code: 'FORN-003',
      name: 'Tintas Industriais Coralux Química Ltda',
      tradeName: 'Coralux Tintas',
      document: '45.123.890/0001-65',
      contactPerson: 'Felipe Barreto',
      email: 'sac@coraluxquimica.com.br',
      phone: '(11) 4880-9900',
      city: 'São Bernardo do Campo',
      state: 'SP',
      deliveryLeadTimeDays: 5,
      suppliedCategories: ['Primers', 'Pintura Eletrostática', 'Solventes'],
      notes: 'Laudo de conformidade técnica em cada lote.',
      createdAt: '2026-01-15T11:00:00Z',
    },
    {
      id: 'sup-04',
      code: 'FORN-004',
      name: 'Madeiras & Painéis Planalto Ltda',
      tradeName: 'Planalto Painéis',
      document: '77.889.900/0001-44',
      contactPerson: 'Renata Lemos',
      email: 'pedidos@planaltomadeiras.com.br',
      phone: '(15) 3322-1100',
      city: 'Sorocaba',
      state: 'SP',
      deliveryLeadTimeDays: 3,
      suppliedCategories: ['MDF Naval', 'Compensados', 'Revestimentos'],
      notes: 'Madeira certificada FSC.',
      createdAt: '2026-01-20T14:20:00Z',
    },
  ],

  rawMaterials: [
    {
      id: 'mat-01',
      code: 'MP-101',
      name: 'Tubo de Aço Carbono 50x50x2mm',
      unit: 'M',
      currentStock: 180,
      minStock: 50,
      unitCost: 28.50,
      supplierId: 'sup-01',
      location: 'Almoxarifado A - RACK-03',
      notes: 'Barras padrão de 6 metros cortadas conforme plano.',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 'mat-02',
      code: 'MP-102',
      name: 'Chapa de Aço Inox 304 - 2.0mm',
      unit: 'M2',
      currentStock: 35,
      minStock: 15,
      unitCost: 145.00,
      supplierId: 'sup-01',
      location: 'Almoxarifado A - GAV-01',
      notes: 'Chapas com película protetora de PVC.',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 'mat-03',
      code: 'MP-103',
      name: 'Parafuso Sextavado M8 x 40mm Aço 8.8 c/ Porca',
      unit: 'UN',
      currentStock: 640,
      minStock: 200,
      unitCost: 1.80,
      supplierId: 'sup-02',
      location: 'Almoxarifado B - PRAT-B12',
      notes: 'Embalagens com 100 unidades.',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 'mat-04',
      code: 'MP-104',
      name: 'Tinta Primer Epóxi Anticorrosivo Cinza',
      unit: 'L',
      currentStock: 14,
      minStock: 20, // Alerta: abaixo do estoque mínimo para demonstração visual!
      unitCost: 52.00,
      supplierId: 'sup-03',
      location: 'Depósito Químico - Q-02',
      notes: 'Estoque baixo! Necessita emissão de requisição.',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 'mat-05',
      code: 'MP-105',
      name: 'Arame de Solda MIG ER70S-6 1.0mm',
      unit: 'KG',
      currentStock: 60,
      minStock: 25,
      unitCost: 22.40,
      supplierId: 'sup-01',
      location: 'Almoxarifado A - CX-SOLDA',
      notes: 'Carretéis de 15kg.',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 'mat-06',
      code: 'MP-106',
      name: 'Tampo MDF Naval 25mm Resistente a Umidade',
      unit: 'M2',
      currentStock: 22,
      minStock: 10,
      unitCost: 95.00,
      supplierId: 'sup-04',
      location: 'Almoxarifado C - PALLET-04',
      notes: 'Dimensão placa padrão 2.75 x 1.83m.',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 'mat-07',
      code: 'MP-107',
      name: 'Sapata Articulada Niveladora M12',
      unit: 'UN',
      currentStock: 96,
      minStock: 40,
      unitCost: 12.50,
      supplierId: 'sup-02',
      location: 'Almoxarifado B - PRAT-B15',
      notes: 'Capacidade de carga 300kg por pé.',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-01-15T10:00:00Z',
    },
  ],

  products: [
    {
      id: 'prod-01',
      code: 'PROD-101',
      name: 'Bancada de Trabalho Industrial Reforçada 2.0x0.9m',
      category: 'Mobiliário Industrial',
      unit: 'UN',
      salePrice: 1280.00,
      description: 'Bancada ergonômica com estrutura tubular 50x50mm, pintura epóxi, sapatas niveladoras e tampo em MDF naval 25mm com borda emborrachada.',
      currentStock: 4,
      materials: [
        { materialId: 'mat-01', quantityPerUnit: 12 },    // 12m tubo
        { materialId: 'mat-03', quantityPerUnit: 16 },    // 16 parafusos
        { materialId: 'mat-04', quantityPerUnit: 1.5 },   // 1.5L primer
        { materialId: 'mat-05', quantityPerUnit: 1.2 },   // 1.2kg solda
        { materialId: 'mat-06', quantityPerUnit: 1.8 },   // 1.8m2 mdf naval
        { materialId: 'mat-07', quantityPerUnit: 4 },     // 4 sapatas
      ],
      processSteps: [
        { id: 'step-01', name: 'Corte e Chanfro de Tubos', standardMinutes: 45, workCenter: 'Corte & Serralheria', description: 'Corte conforme plano de corte PC-101' },
        { id: 'step-02', name: 'Soldagem e Montagem da Armação', standardMinutes: 90, workCenter: 'Solda & Caldeiraria', description: 'Solda MIG contínua e esmerilhamento de rebarbas' },
        { id: 'step-03', name: 'Pintura Epóxi Anticorrosiva', standardMinutes: 60, workCenter: 'Pintura & Acabamento', description: 'Aplicação de primer e acabamento cinza martelado' },
        { id: 'step-04', name: 'Fixação Tampo e Montagem Final', standardMinutes: 35, workCenter: 'Montagem Final & Embalagem', description: 'Fixação de tampo naval e sapatas niveladoras' },
        { id: 'step-05', name: 'Inspeção de Qualidade e Embalagem', standardMinutes: 20, workCenter: 'Controle de Qualidade', description: 'Checagem dimensional, esquadro e teste de carga estática' },
      ],
      totalStandardTimeMinutes: 250, // 4h10min
      estimatedMaterialCost: 669.78,
      createdAt: '2026-01-20T09:00:00Z',
      updatedAt: '2026-01-20T09:00:00Z',
    },
    {
      id: 'prod-02',
      code: 'PROD-102',
      name: 'Painel de Comando Metálico IP65 800x600x250mm',
      category: 'Quadros & Painéis',
      unit: 'UN',
      salePrice: 890.00,
      description: 'Gabinete metálico estanque com chapa de inox dobrada, fecho fenda/chave Yale e vedação impermeabilizante.',
      currentStock: 8,
      materials: [
        { materialId: 'mat-02', quantityPerUnit: 1.6 },   // 1.6 m2 inox
        { materialId: 'mat-03', quantityPerUnit: 8 },     // 8 parafusos
        { materialId: 'mat-04', quantityPerUnit: 0.8 },   // 0.8L tinta
        { materialId: 'mat-05', quantityPerUnit: 0.5 },   // 0.5kg solda
      ],
      processSteps: [
        { id: 'step-06', name: 'Guilhotina e Dobra CNC', standardMinutes: 30, workCenter: 'Corte & Serralheria', description: 'Dobra precisa conforme projeto elétrico' },
        { id: 'step-07', name: 'Solda TIG/MIG das Junções', standardMinutes: 40, workCenter: 'Solda & Caldeiraria', description: 'Soldagem estanque para atendimento a norma IP65' },
        { id: 'step-08', name: 'Pintura e Secagem em Estufa', standardMinutes: 50, workCenter: 'Pintura & Acabamento', description: 'Camada de 80 micras de tinta poliéster' },
        { id: 'step-09', name: 'Instalação de Borracha e Fechos', standardMinutes: 25, workCenter: 'Montagem Final & Embalagem', description: 'Colagem de perfil de borracha e fechaduras' },
        { id: 'step-10', name: 'Teste de Estanqueidade e CQ', standardMinutes: 15, workCenter: 'Controle de Qualidade', description: 'Teste de vedação com ar comprimido e laudo visual' },
      ],
      totalStandardTimeMinutes: 160, // 2h40min
      estimatedMaterialCost: 299.20,
      createdAt: '2026-01-22T10:30:00Z',
      updatedAt: '2026-01-22T10:30:00Z',
    },
    {
      id: 'prod-03',
      code: 'PROD-103',
      name: 'Rack Modular Autoportante para Paletes 2000kg',
      category: 'Estruturas de Armazenagem',
      unit: 'UN',
      salePrice: 1650.00,
      description: 'Módulo estrutural pesado com travessas reforçadas em aço e pintura de alta visibilidade.',
      currentStock: 2,
      materials: [
        { materialId: 'mat-01', quantityPerUnit: 24 },    // 24m tubo
        { materialId: 'mat-03', quantityPerUnit: 24 },    // 24 parafusos
        { materialId: 'mat-04', quantityPerUnit: 2.2 },   // 2.2L primer
        { materialId: 'mat-05', quantityPerUnit: 2.0 },   // 2.0kg solda
        { materialId: 'mat-07', quantityPerUnit: 4 },     // 4 sapatas
      ],
      processSteps: [
        { id: 'step-11', name: 'Corte e Furação de Colunas', standardMinutes: 60, workCenter: 'Corte & Serralheria', description: 'Furação padrão com passo de 50mm' },
        { id: 'step-12', name: 'Solda Estrutural dos Longarinas', standardMinutes: 110, workCenter: 'Solda & Caldeiraria', description: 'Gabarito de montagem com travessas diagonais' },
        { id: 'step-13', name: 'Pintura Laranja Segurança / Cinza', standardMinutes: 70, workCenter: 'Pintura & Acabamento', description: 'Pintura com alta resistência a abrasão' },
        { id: 'step-14', name: 'Identificação de Carga e Embalagem', standardMinutes: 30, workCenter: 'Controle de Qualidade', description: 'Afixação de plaqueta técnica de capacidade' },
      ],
      totalStandardTimeMinutes: 270, // 4h30min
      estimatedMaterialCost: 936.60,
      createdAt: '2026-01-25T11:15:00Z',
      updatedAt: '2026-01-25T11:15:00Z',
    },
  ],

  clients: [
    {
      id: 'cli-01',
      code: 'CLI-001',
      name: 'Indústria Alimentícia Bela Vista S/A',
      tradeName: 'Alimentos Bela Vista',
      document: '33.444.555/0001-88',
      email: 'compras@belavistaalimentos.com.br',
      phone: '(11) 4700-3300',
      contactPerson: 'Juliana Paes (Suprimentos)',
      address: {
        street: 'Avenida das Indústrias',
        number: '1420',
        complement: 'Galpão 3',
        neighborhood: 'Distrito Industrial',
        city: 'Jundiaí',
        state: 'SP',
        zipCode: '13213-000',
      },
      notes: 'Exige certificado de conformidade do lote e laudo técnico assinado.',
      createdAt: '2026-01-05T08:00:00Z',
    },
    {
      id: 'cli-02',
      code: 'CLI-002',
      name: 'Progresso Autopeças e Montagens Ltda',
      tradeName: 'Progresso Auto',
      document: '55.666.777/0001-12',
      email: 'engenharia@progressoauto.com.br',
      phone: '(19) 3888-2211',
      contactPerson: 'Ricardo Silveira',
      address: {
        street: 'Rua General Osório',
        number: '850',
        neighborhood: 'Vila Industrial',
        city: 'Campinas',
        state: 'SP',
        zipCode: '13035-100',
      },
      notes: 'Cliente recorrente. Faturamento a prazo 28 DDL.',
      createdAt: '2026-01-08T10:00:00Z',
    },
    {
      id: 'cli-03',
      code: 'CLI-003',
      name: 'Construtora e Incorporadora Horizonte Engenharia',
      tradeName: 'Horizonte Construtora',
      document: '66.777.888/0001-99',
      email: 'obras@horizonteeng.com.br',
      phone: '(11) 3105-8899',
      contactPerson: 'Eng. Marcelo Prado',
      address: {
        street: 'Alameda Santos',
        number: '2100',
        complement: 'Conj. 82',
        neighborhood: 'Cerqueira César',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01418-200',
      },
      notes: 'Entregas agendadas diretamente nos canteiros de obra.',
      createdAt: '2026-01-14T14:40:00Z',
    },
  ],

  capacities: [
    {
      id: 'cap-01',
      code: 'LINHA-01',
      name: 'Setor de Corte & Serralheria',
      dailyCapacityHours: 16,
      activeWorkers: 3,
      shiftType: '2 Turnos (06h-14h / 14h-22h)',
      efficiencyRate: 88,
      status: 'OPERACIONAL',
      notes: '2 serras de fita automáticas, 1 guilhotina hidráulica.',
    },
    {
      id: 'cap-02',
      code: 'LINHA-02',
      name: 'Setor de Soldagem & Caldeiraria',
      dailyCapacityHours: 16,
      activeWorkers: 4,
      shiftType: '2 Turnos (06h-14h / 14h-22h)',
      efficiencyRate: 85,
      status: 'OPERACIONAL',
      notes: '4 postos de solda MIG/MAG e 1 posto TIG com exaustão.',
    },
    {
      id: 'cap-03',
      code: 'LINHA-03',
      name: 'Cabine de Pintura & Acabamento',
      dailyCapacityHours: 8,
      activeWorkers: 2,
      shiftType: '1 Turno Comercial (07h às 17h)',
      efficiencyRate: 92,
      status: 'OPERACIONAL',
      notes: 'Cabine de pintura eletrostática a pó e estufa de polimerização.',
    },
    {
      id: 'cap-04',
      code: 'LINHA-04',
      name: 'Bancada de Montagem Final & CQ',
      dailyCapacityHours: 8,
      activeWorkers: 3,
      shiftType: '1 Turno Comercial (07h às 17h)',
      efficiencyRate: 95,
      status: 'OPERACIONAL',
      notes: 'Inspeção dimensional, montagem eletromecânica e embalagem técnica.',
    },
  ],

  orders: [
    {
      id: 'ord-01',
      orderNumber: 'PED-2026-001',
      clientId: 'cli-01',
      clientName: 'Indústria Alimentícia Bela Vista S/A',
      orderDate: '2026-10-01',
      deliveryDate: '2026-10-18',
      items: [
        {
          productId: 'prod-01',
          productCode: 'PROD-101',
          productName: 'Bancada de Trabalho Industrial Reforçada 2.0x0.9m',
          quantity: 5,
          unitPrice: 1280.00,
          totalPrice: 6400.00,
        },
      ],
      totalAmount: 6400.00,
      status: 'EM_PRODUCAO',
      notes: 'Entrega urgente para expansão da linha de envase.',
      productionOrderId: 'op-01',
      createdAt: '2026-10-01T09:15:00Z',
    },
    {
      id: 'ord-02',
      orderNumber: 'PED-2026-002',
      clientId: 'cli-02',
      clientName: 'Progresso Autopeças e Montagens Ltda',
      orderDate: '2026-10-03',
      deliveryDate: '2026-10-22',
      items: [
        {
          productId: 'prod-02',
          productCode: 'PROD-102',
          productName: 'Painel de Comando Metálico IP65 800x600x250mm',
          quantity: 10,
          unitPrice: 890.00,
          totalPrice: 8900.00,
        },
      ],
      totalAmount: 8900.00,
      status: 'PENDENTE',
      notes: 'Aguardando validação do desenho técnico final.',
      createdAt: '2026-10-03T11:00:00Z',
    },
    {
      id: 'ord-03',
      orderNumber: 'PED-2026-003',
      clientId: 'cli-03',
      clientName: 'Construtora e Incorporadora Horizonte Engenharia',
      orderDate: '2026-09-20',
      deliveryDate: '2026-10-05',
      items: [
        {
          productId: 'prod-03',
          productCode: 'PROD-103',
          productName: 'Rack Modular Autoportante para Paletes 2000kg',
          quantity: 2,
          unitPrice: 1650.00,
          totalPrice: 3300.00,
        },
      ],
      totalAmount: 3300.00,
      status: 'CONCLUIDO',
      notes: 'Pedido faturado e entregue com sucesso.',
      productionOrderId: 'op-03',
      createdAt: '2026-09-20T14:00:00Z',
    },
  ],

  productionOrders: [
    {
      id: 'op-01',
      code: 'OP-2026-001',
      orderId: 'ord-01',
      orderNumber: 'PED-2026-001',
      clientName: 'Indústria Alimentícia Bela Vista S/A',
      productId: 'prod-01',
      productCode: 'PROD-101',
      productName: 'Bancada de Trabalho Industrial Reforçada 2.0x0.9m',
      quantity: 5,
      unit: 'UN',
      lotNumber: 'LOTE-2610-A1',
      status: 'EM_PRODUCAO',
      issueDate: '2026-10-02',
      startDate: '2026-10-04T08:00:00Z',
      targetDate: '2026-10-15',
      technicalResponsibleId: 'user-01',
      technicalResponsibleName: 'Eng. Carlos Eduardo Silva',
      technicalResponsibleRegistration: 'CREA-SP 506.912/D',
      capacityId: 'cap-02',
      capacityName: 'Setor de Soldagem & Caldeiraria',
      materials: [
        {
          materialId: 'mat-01',
          materialCode: 'MP-101',
          materialName: 'Tubo de Aço Carbono 50x50x2mm',
          requiredQuantity: 60, // 5 * 12
          unit: 'M',
          availableStock: 180,
          unitCost: 28.50,
          totalCost: 1710.00,
          isAvailable: true,
        },
        {
          materialId: 'mat-03',
          materialCode: 'MP-103',
          materialName: 'Parafuso Sextavado M8 x 40mm Aço 8.8 c/ Porca',
          requiredQuantity: 80, // 5 * 16
          unit: 'UN',
          availableStock: 640,
          unitCost: 1.80,
          totalCost: 144.00,
          isAvailable: true,
        },
        {
          materialId: 'mat-04',
          materialCode: 'MP-104',
          materialName: 'Tinta Primer Epóxi Anticorrosivo Cinza',
          requiredQuantity: 7.5, // 5 * 1.5
          unit: 'L',
          availableStock: 14,
          unitCost: 52.00,
          totalCost: 390.00,
          isAvailable: true,
        },
        {
          materialId: 'mat-05',
          materialCode: 'MP-105',
          materialName: 'Arame de Solda MIG ER70S-6 1.0mm',
          requiredQuantity: 6.0, // 5 * 1.2
          unit: 'KG',
          availableStock: 60,
          unitCost: 22.40,
          totalCost: 134.40,
          isAvailable: true,
        },
        {
          materialId: 'mat-06',
          materialCode: 'MP-106',
          materialName: 'Tampo MDF Naval 25mm Resistente a Umidade',
          requiredQuantity: 9.0, // 5 * 1.8
          unit: 'M2',
          availableStock: 22,
          unitCost: 95.00,
          totalCost: 855.00,
          isAvailable: true,
        },
        {
          materialId: 'mat-07',
          materialCode: 'MP-107',
          materialName: 'Sapata Articulada Niveladora M12',
          requiredQuantity: 20, // 5 * 4
          unit: 'UN',
          availableStock: 96,
          unitCost: 12.50,
          totalCost: 250.00,
          isAvailable: true,
        },
      ],
      processSteps: [
        { id: 'step-01', name: 'Corte e Chanfro de Tubos', standardMinutes: 225, workCenter: 'Corte & Serralheria', description: 'Corte conforme plano de corte PC-101 (5 un)' },
        { id: 'step-02', name: 'Soldagem e Montagem da Armação', standardMinutes: 450, workCenter: 'Solda & Caldeiraria', description: 'Solda MIG contínua e esmerilhamento (5 un)' },
        { id: 'step-03', name: 'Pintura Epóxi Anticorrosiva', standardMinutes: 300, workCenter: 'Pintura & Acabamento', description: 'Aplicação de primer e acabamento cinza (5 un)' },
        { id: 'step-04', name: 'Fixação Tampo e Montagem Final', standardMinutes: 175, workCenter: 'Montagem Final & Embalagem', description: 'Fixação de tampo naval e sapatas (5 un)' },
        { id: 'step-05', name: 'Inspeção de Qualidade e Embalagem', standardMinutes: 100, workCenter: 'Controle de Qualidade', description: 'Checagem dimensional e esquadro (5 un)' },
      ],
      plannedTotalMinutes: 1250, // 20.8h
      actualTotalMinutes: 630, // Apontado até o momento
      timeLogs: [
        {
          id: 'log-01',
          stepId: 'step-01',
          stepName: 'Corte e Chanfro de Tubos',
          operatorName: 'Roberto Antunes Costa',
          startTime: '2026-10-04T08:00:00Z',
          endTime: '2026-10-04T11:40:00Z',
          durationMinutes: 220,
          producedQuantity: 5,
          notes: 'Todos os 60 metros de tubo cortados e chanfrados com sucesso.',
          loggedByUserId: 'user-01',
          loggedByUserName: 'Eng. Carlos Eduardo Silva',
        },
        {
          id: 'log-02',
          stepId: 'step-02',
          stepName: 'Soldagem e Montagem da Armação',
          operatorName: 'Lúcio Mauro (Soldador)',
          startTime: '2026-10-05T08:00:00Z',
          endTime: '2026-10-05T14:50:00Z',
          durationMinutes: 410,
          producedQuantity: 5,
          notes: 'Armações soldadas no gabarito padrão. Esquadro conferido.',
          loggedByUserId: 'user-01',
          loggedByUserName: 'Eng. Carlos Eduardo Silva',
        },
      ],
      notes: 'Prioridade alta para liberação no dia 15.',
      createdAt: '2026-10-02T10:00:00Z',
      updatedAt: '2026-10-05T15:00:00Z',
    },
    {
      id: 'op-02',
      code: 'OP-2026-002',
      productId: 'prod-02',
      productCode: 'PROD-102',
      productName: 'Painel de Comando Metálico IP65 800x600x250mm',
      quantity: 6,
      unit: 'UN',
      lotNumber: 'LOTE-2610-B2',
      status: 'SEPARACAO',
      issueDate: '2026-10-06',
      targetDate: '2026-10-20',
      technicalResponsibleId: 'user-01',
      technicalResponsibleName: 'Eng. Carlos Eduardo Silva',
      technicalResponsibleRegistration: 'CREA-SP 506.912/D',
      capacityId: 'cap-01',
      capacityName: 'Setor de Corte & Serralheria',
      materials: [
        {
          materialId: 'mat-02',
          materialCode: 'MP-102',
          materialName: 'Chapa de Aço Inox 304 - 2.0mm',
          requiredQuantity: 9.6,
          unit: 'M2',
          availableStock: 35,
          unitCost: 145.00,
          totalCost: 1392.00,
          isAvailable: true,
        },
        {
          materialId: 'mat-03',
          materialCode: 'MP-103',
          materialName: 'Parafuso Sextavado M8 x 40mm Aço 8.8 c/ Porca',
          requiredQuantity: 48,
          unit: 'UN',
          availableStock: 640,
          unitCost: 1.80,
          totalCost: 86.40,
          isAvailable: true,
        },
        {
          materialId: 'mat-04',
          materialCode: 'MP-104',
          materialName: 'Tinta Primer Epóxi Anticorrosivo Cinza',
          requiredQuantity: 4.8,
          unit: 'L',
          availableStock: 14,
          unitCost: 52.00,
          totalCost: 249.60,
          isAvailable: true,
        },
        {
          materialId: 'mat-05',
          materialCode: 'MP-105',
          materialName: 'Arame de Solda MIG ER70S-6 1.0mm',
          requiredQuantity: 3.0,
          unit: 'KG',
          availableStock: 60,
          unitCost: 22.40,
          totalCost: 67.20,
          isAvailable: true,
        },
      ],
      processSteps: [
        { id: 'step-06', name: 'Guilhotina e Dobra CNC', standardMinutes: 180, workCenter: 'Corte & Serralheria', description: 'Dobra precisa (6 un)' },
        { id: 'step-07', name: 'Solda TIG/MIG das Junções', standardMinutes: 240, workCenter: 'Solda & Caldeiraria', description: 'Soldagem estanque IP65 (6 un)' },
        { id: 'step-08', name: 'Pintura e Secagem em Estufa', standardMinutes: 300, workCenter: 'Pintura & Acabamento', description: 'Pintura poliéster cinza (6 un)' },
        { id: 'step-09', name: 'Instalação de Borracha e Fechos', standardMinutes: 150, workCenter: 'Montagem Final & Embalagem', description: 'Borracha e fecho yale (6 un)' },
        { id: 'step-10', name: 'Teste de Estanqueidade e CQ', standardMinutes: 90, workCenter: 'Controle de Qualidade', description: 'Laudo de inspeção IP65 (6 un)' },
      ],
      plannedTotalMinutes: 960,
      actualTotalMinutes: 0,
      timeLogs: [],
      notes: 'Produção para estoque de segurança e pronta entrega.',
      createdAt: '2026-10-06T14:00:00Z',
      updatedAt: '2026-10-06T14:00:00Z',
    },
    {
      id: 'op-03',
      code: 'OP-2026-003',
      orderId: 'ord-03',
      orderNumber: 'PED-2026-003',
      clientName: 'Construtora e Incorporadora Horizonte Engenharia',
      productId: 'prod-03',
      productCode: 'PROD-103',
      productName: 'Rack Modular Autoportante para Paletes 2000kg',
      quantity: 2,
      unit: 'UN',
      lotNumber: 'LOTE-2609-C3',
      status: 'CONCLUIDA',
      issueDate: '2026-09-22',
      startDate: '2026-09-23T08:00:00Z',
      targetDate: '2026-10-03',
      completedDate: '2026-10-02T16:45:00Z',
      technicalResponsibleId: 'user-01',
      technicalResponsibleName: 'Eng. Carlos Eduardo Silva',
      technicalResponsibleRegistration: 'CREA-SP 506.912/D',
      capacityId: 'cap-02',
      capacityName: 'Setor de Soldagem & Caldeiraria',
      materials: [
        {
          materialId: 'mat-01',
          materialCode: 'MP-101',
          materialName: 'Tubo de Aço Carbono 50x50x2mm',
          requiredQuantity: 48,
          unit: 'M',
          availableStock: 180,
          unitCost: 28.50,
          totalCost: 1368.00,
          isAvailable: true,
        },
        {
          materialId: 'mat-03',
          materialCode: 'MP-103',
          materialName: 'Parafuso Sextavado M8 x 40mm Aço 8.8 c/ Porca',
          requiredQuantity: 48,
          unit: 'UN',
          availableStock: 640,
          unitCost: 1.80,
          totalCost: 86.40,
          isAvailable: true,
        },
      ],
      processSteps: [
        { id: 'step-11', name: 'Corte e Furação de Colunas', standardMinutes: 120, workCenter: 'Corte & Serralheria', description: 'Corte de colunas (2 un)' },
        { id: 'step-12', name: 'Solda Estrutural dos Longarinas', standardMinutes: 220, workCenter: 'Solda & Caldeiraria', description: 'Gabarito estrutural (2 un)' },
        { id: 'step-13', name: 'Pintura Laranja Segurança / Cinza', standardMinutes: 140, workCenter: 'Pintura & Acabamento', description: 'Pintura eletrostática (2 un)' },
        { id: 'step-14', name: 'Identificação de Carga e Embalagem', standardMinutes: 60, workCenter: 'Controle de Qualidade', description: 'Plaqueta técnica e ensaio (2 un)' },
      ],
      plannedTotalMinutes: 540,
      actualTotalMinutes: 520,
      timeLogs: [
        {
          id: 'log-03',
          stepId: 'step-11',
          stepName: 'Corte e Furação de Colunas',
          operatorName: 'Roberto Antunes Costa',
          startTime: '2026-09-23T08:00:00Z',
          endTime: '2026-09-23T10:00:00Z',
          durationMinutes: 120,
          producedQuantity: 2,
          notes: 'Furações executadas com precisão milimétrica.',
          loggedByUserId: 'user-01',
          loggedByUserName: 'Eng. Carlos Eduardo Silva',
        },
        {
          id: 'log-04',
          stepId: 'step-12',
          stepName: 'Solda Estrutural dos Longarinas',
          operatorName: 'Lúcio Mauro',
          startTime: '2026-09-24T08:00:00Z',
          endTime: '2026-09-24T11:30:00Z',
          durationMinutes: 210,
          producedQuantity: 2,
          notes: 'Soldagem inspecionada por líquido penetrante.',
          loggedByUserId: 'user-01',
          loggedByUserName: 'Eng. Carlos Eduardo Silva',
        },
        {
          id: 'log-05',
          stepId: 'step-13',
          stepName: 'Pintura Laranja Segurança / Cinza',
          operatorName: 'Marcos Tintas',
          startTime: '2026-09-26T09:00:00Z',
          endTime: '2026-09-26T11:10:00Z',
          durationMinutes: 130,
          producedQuantity: 2,
          notes: 'Polimerização em estufa 200°C por 25 min.',
          loggedByUserId: 'user-01',
          loggedByUserName: 'Eng. Carlos Eduardo Silva',
        },
        {
          id: 'log-06',
          stepId: 'step-14',
          stepName: 'Identificação de Carga e Embalagem',
          operatorName: 'Roberto Antunes Costa',
          startTime: '2026-10-02T15:45:00Z',
          endTime: '2026-10-02T16:45:00Z',
          durationMinutes: 60,
          producedQuantity: 2,
          notes: 'Ensaio de carga estática aprovado 2000kg. Liberado com laudo.',
          loggedByUserId: 'user-01',
          loggedByUserName: 'Eng. Carlos Eduardo Silva',
        },
      ],
      completedQuantity: 2,
      scrapQuantity: 0,
      qualityNotes: 'Lote aprovado em 100% dos testes mecânicos. Conformidade com norma ABNT NBR 15524.',
      createdAt: '2026-09-22T08:00:00Z',
      updatedAt: '2026-10-02T16:45:00Z',
    },
  ],
};
